function(dang_include_finder)
  include(${ARGN})
  string(REPLACE ";" " " FINDER "include(${ARGN})")
  if(NOT ${FINDER} IN_LIST DANG_FINDERS)
    set(DANG_FINDERS ${DANG_FINDERS} ${FINDER} CACHE INTERNAL "finder")
  endif()
endfunction()
