# Taken and modified from here:
# https://github.com/lukka/CppBuildTasks-Validation/blob/master/.github/workflows/hosted-pure-workflow.yml

name: Run build and tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  job:
    name: ${{matrix.runs.name}}
    runs-on: ${{matrix.runs.os}}
    strategy:
      fail-fast: false
      matrix:
        runs:
          - name: Ubuntu - gcc
            os: ubuntu-latest
            compiler: g++
          - name: Ubuntu - clang
            os: ubuntu-latest
            compiler: clang++
          - name: Windows - cl
            os: windows-latest
            compiler: cl
          - name: Windows - clang
            os: windows-latest
            compiler: clang-cl

    env:
      CMAKE_BUILD_DIR: ${{github.workspace}}/build/
      VCPKG_ROOT: ${{github.workspace}}/vcpkg

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Restore vcpkg and its artifacts
        uses: actions/cache@v2
        env:
          vcpkg-cache-base: vcpkg-${{hashFiles('.git/modules/vcpkg/HEAD')}}-${{runner.os}}
        with:
          path: |
            ${{env.CMAKE_BUILD_DIR}}/vcpkg_installed/
            ${{env.VCPKG_ROOT}}
            !${{env.VCPKG_ROOT}}/buildtrees
            !${{env.VCPKG_ROOT}}/packages
            !${{env.VCPKG_ROOT}}/downloads
            !${{env.VCPKG_ROOT}}/installed
          key: ${{env.vcpkg-cache-base}}-${{hashFiles('vcpkg.json')}}
          restore-keys: |
            ${{env.vcpkg-cache-base}}-

      - name: (Linux) Install required tools for glfw
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev

      - name: (Windows) Ensure the Developer Command Prompt is setup correctly
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install dependencies and generate project files
        run: cmake -S "${{github.workspace}}" -B "${{env.CMAKE_BUILD_DIR}}" -GNinja -DCMAKE_CXX_COMPILER=${{matrix.runs.compiler}} -DDANG_WERROR:BOOL=ON

      - name: Build all
        run: cmake --build "${{env.CMAKE_BUILD_DIR}}"

      - name: Build dmath
        run: cmake --build "${{env.CMAKE_BUILD_DIR}}" --target dmath

      - name: Run tests
        run: |
          cd "${{env.CMAKE_BUILD_DIR}}"
          ctest --parallel 2 --label-exclude "^opengl$"
