# Used to skip the "Run build and tests" workflow if no build related files changed.

name: Run build and tests

on:
  push:
    branches:
      - master
    paths:
      - .*
      - naming-conventions.md
      - README.md
      - run-clang-format.bat
      - run-cmake-format.bat
      - run-cmake-lint.bat
      - VSWorkspaceSettings.json
      - "**.natvis"
  pull_request:
    branches:
      - master
    paths:
      - .*
      - naming-conventions.md
      - README.md
      - run-clang-format.bat
      - run-cmake-format.bat
      - run-cmake-lint.bat
      - VSWorkspaceSettings.json
      - "**.natvis"

jobs:
  job:
    name: ${{matrix.runs.name}}
    runs-on: ${{matrix.runs.os}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu - GCC
            os: ubuntu-latest
            preset: linux-gcc-x64
          - name: Ubuntu - Clang
            os: ubuntu-latest
            preset: linux-clang-x64
          - name: Windows - MSVC
            os: windows-latest
            preset: windows-msvc-x64
          - name: Windows - Clang
            os: windows-latest
            preset: windows-clang-x64

    steps:
      - run: "echo No build related files changed; skipping build and tests."
